### ISSUE TITLE
_pickle.UnpicklingError: unpickling stack underflow

### ISSUE THREAD

**Issue by stoneLuo1991** [DrSleep/light-weight-refinenet#50]
hello, i meet some problems now. when i try "To start training on NYU:" this part, i got "Connected to pydev debugger (build 182.3911.33)
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/luo/Documents/code/light-weight-refinenet/src/train.py", line 435, in <module>
    main()
  File "/Users/luo/Documents/code/light-weight-refinenet/src/train.py", line 364, in main
    create_segmenter(args.enc, args.enc_pretrained, args.num_classes[0])
  File "/Users/luo/Documents/code/light-weight-refinenet/src/train.py", line 136, in create_segmenter
    return rf_lw50(num_classes, imagenet=pretrained)
  File "/Users/luo/Documents/code/light-weight-refinenet/models/resnet.py", line 249, in rf_lw50
    model.load_state_dict(maybe_download(key, url), strict=False)
  File "/Users/luo/Documents/code/light-weight-refinenet/utils/helpers.py", line 22, in maybe_download
    return torch.load(cached_file, map_location=map_location)
  File "/Users/luo/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/Users/luo/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 532, in _load
    magic_number = pickle_module.load(f)
_pickle.UnpicklingError: unpickling stack underflow

Process finished with exit code 1
"
can you help me to solve this? thx

**Comment by cyw233** [comment]
Have you fixed this problem? I have the same issue today...
